#!/bin/bash

echo "=== Setting up Ingress for PiggyMetrics ==="
echo ""
echo "Step 1: Add domain to /etc/hosts"
echo "Run this command:"
echo "  sudo bash -c 'echo \"127.0.0.1 piggymetrics.local\" >> /etc/hosts'"
echo ""
echo "Step 2: Verify the entry was added:"
echo "  cat /etc/hosts | grep piggymetrics"
echo ""
echo "Step 3: Access your application at:"
echo "  http://piggymetrics.local"
echo ""
echo "=== Troubleshooting ==="
echo "If the domain doesn't work, check:"
echo "  kubectl get ingress -n piggymetricss"
echo "  kubectl get pods -n ingress-nginx"
echo "  kubectl get svc -n piggymetricss gateway"
