apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: piggymetricss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      initContainers:
      - name: wait-for-config
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z config-service.piggymetricss.svc.cluster.local 8888; do echo waiting for config; sleep 5; done']
      - name: wait-for-registry
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z registry-service.piggymetricss.svc.cluster.local 8761; do echo waiting for registry; sleep 5; done']
      containers:
      - name: gateway
        image: asha515/piggymetrics-gateway:20251130-102929-1ebdf20
        ports:
        - containerPort: 4000
        env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: piggymetrics-config
              key: CONFIG_SERVICE_PASSWORD
        readinessProbe:
          httpGet:
            path: /
            port: 4000
          initialDelaySeconds: 180
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /
            port: 4000
          initialDelaySeconds: 240
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: piggymetricss
spec:
  selector:
    app: gateway
  ports:
  - port: 80
    targetPort: 4000
  type: ClusterIP
  