apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring
  namespace: piggymetricss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      initContainers:
      - name: wait-for-config
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z config-service.piggymetricss.svc.cluster.local 8888; do echo waiting for config; sleep 5; done']
      containers:
      - name: monitoring
        image: asha515/piggymetrics-monitoring:20251130-104202-399530e
        ports:
        - containerPort: 8080
        env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: piggymetrics-config
              key: CONFIG_SERVICE_PASSWORD
        readinessProbe:
          httpGet:
            path: /hystrix
            port: 8080
          initialDelaySeconds: 180
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /hystrix
            port: 8080
          initialDelaySeconds: 240
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: monitoring
  namespace: piggymetricss
spec:
  selector:
    app: monitoring
  ports:
  - port: 8080
    targetPort: 8080
  type: NodePort