apiVersion: apps/v1
kind: Deployment
metadata:
  name: turbine-stream-service
  namespace: piggymetricss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: turbine-stream-service
  template:
    metadata:
      labels:
        app: turbine-stream-service
    spec:
      initContainers:
      - name: wait-for-config
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z config-service 8888; do echo waiting for config; sleep 5; done']
      containers:
      - name: turbine-stream-service
        image: asha515/piggymetrics-turbine-stream-service:20251130-073455-b88f079
        ports:
        - containerPort: 8989
        env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: piggymetrics-config
              key: CONFIG_SERVICE_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: turbine-stream-service
  namespace: piggymetricss
spec:
  selector:
    app: turbine-stream-service
  ports:
  - port: 8989
    targetPort: 8989
  type: ClusterIP